### ISSUE TITLE
Error in ios 9.3

### ISSUE THREAD

**Issue by AlbertoMrFz** [kaishin/ImageScout#16]
Hi, i use IOS 9.3 and the log not print anithing

let scout = ImageScout()

scout.scoutImageWithURI("http://.../image-scout-logo.png") { error, size, type in
  if let unwrappedError = error {
    println(unwrappedError.code)
  } else {
    println("Size: \(size)")
    println("Type: \(type.rawValue)")
  }
}

**Comment by kaishin** [comment]
This code snippet is deprecated. Please install 1.0 and try again with the new example.
