### ISSUE TITLE
error to run demo on device(iPhone5S)

### ISSUE THREAD

**Issue by wangbourne** [kaishin/ImageScout#7]
with error:
dyld: Library not loaded: @rpath/ImageScout.framework/ImageScout
  Referenced from: /private/var/mobile/Containers/Bundle/Application/F9A9E333-019B-46B8-8DA9-CA5B4437D2C3/Demo.app/Demo
  Reason: image not found

**Comment by kaishin** [comment]
This should be fixed in f9db4fe now. Otherwise I can reopen.
