### ISSUE TITLE
Build failure on  Carthage

### ISSUE THREAD

**Issue by wangbourne** [kaishin/ImageScout#8]
with error code:
The following build commands failed:
	CompileSwift normal arm64 /Users/BourneWang/Desktop/ImageScout-master/Demo/Carthage/Checkouts/ImageScout/Source/ImageScout.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by kaishin** [comment]
Can you try again and see if you still get the error?
